### PR TITLE
Test jenkins tests

### PR DESCRIPTION
**Pull request by nclopezo**
Please don't merge this!

### CODE REVIEW

**Comment by nclopezo** [comment]
The checks library is still in beta state and available only for apps. I will try to use the pr reviews instead.

**Comment by nclopezo** [comment]
or just the pr comments and labels

**Comment by juanfmx2** [comment]
Hello chembl-bot! how ya doin?

**Comment by nclopezo** [comment]
Thanks @chembl-bot !!!

**Pull request closed without merging**
